In [18]:
## 212223240124
## PREM R

In [1]:
import cv2

In [1]:
import torch
import numpy as np

In [2]:
np.random.seed(42)
torch.manual_seed(42)

In [3]:
arr = np.random.randint(0, 5, 6)

In [4]:
arr

array([3, 4, 2, 4, 4, 1], dtype=int32)

In [6]:
x = torch.from_numpy(arr)

In [8]:
x = x.type(torch.int64)

In [9]:
x

tensor([3, 4, 2, 4, 4, 1])

In [10]:
x = x.reshape(3, 2)

In [11]:
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [12]:
x[:, 1]

tensor([4, 4, 1])

In [13]:
x ** 2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [14]:
y = torch.randint(0, 5, (2, 3))

In [15]:
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [16]:
torch.matmul(x, y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])